'use client';
import {createContext,useContext,useState,useEffect,useRef,ReactNode,MouseEvent} from 'react';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {Search,ShoppingBag,Menu,Minus,Plus,Trash2,UserRound} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Line,lineKey,categories,products,getProduct,subtotal,money,shipping} from '@/lib/catalog';
import {SourceImage,Model} from './image';
import {OpeningSequence} from './opening';
type Shop={lines:Line[];busy:boolean;ready:boolean;paymentReady:boolean;add:(l:Line)=>Promise<boolean>;change:(l:Line,q:number)=>Promise<void>;openCart:()=>void;quick:(id:string)=>void;go:(url:string)=>void};
const Context=createContext<Shop>(null!);export const useShop=()=>useContext(Context);
export function Go({href,children,className='',transition=false,onClick,...rest}:{href:string;children:ReactNode;className?:string;transition?:boolean;[k:string]:unknown}){const s=useShop();return <Link href={href} className={className} {...rest} onClick={(e:MouseEvent<HTMLAnchorElement>)=>{if(typeof onClick==='function')onClick(e);if(href.includes('#')&&!e.metaKey&&!e.ctrlKey){const [path,hash]=href.split('#');if(!path||path===window.location.pathname){const target=document.getElementById(hash);if(target){e.preventDefault();history.replaceState(null,'',href);target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});return}}}if(transition&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey){e.preventDefault();s.go(href)}}}>{children}</Link>}
export function StoreProvider({children}:{children:ReactNode}){
 const [lines,setLines]=useState<Line[]>([]),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[paymentReady,setPaymentReady]=useState(false),[cart,setCart]=useState(false),[menu,setMenu]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[quickId,setQuickId]=useState<string|null>(null),[size,setSize]=useState(''),[tiles,setTiles]=useState(false),[dark,setDark]=useState(false),[compact,setCompact]=useState(false),[categoryCover,setCategoryCover]=useState<number|null>(null);
 const pathname=usePathname(),router=useRouter(),lock=useRef(false),timers=useRef<ReturnType<typeof setTimeout>[]>([]);const quickProduct=getProduct(quickId||'');
 useEffect(()=>{fetch('/api/cart').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{lines:Line[]}>}).then(d=>{setLines(d.lines);setReady(true)}).catch(()=>toast.error('Your bag could not load. Refresh to try again.'));fetch('/api/store').then(r=>r.json() as Promise<{paymentReady:boolean}>).then(d=>setPaymentReady(d.paymentReady)).catch(()=>{});return()=>timers.current.forEach(clearTimeout)},[]);
 useEffect(()=>{setMenu(false);setSearch(false);setCart(false);setQuickId(null);if(window.location.hash){const hash=decodeURIComponent(window.location.hash.slice(1));timers.current.push(setTimeout(()=>document.getElementById(hash)?.scrollIntoView({behavior:'instant'}),120))}const title=document.querySelector('h1');if(title){title.setAttribute('tabindex','-1')}},[pathname]);
 useEffect(()=>{let pending=false;const update=()=>{pending=false;setCompact(window.scrollY>50);const sections=Array.from(document.querySelectorAll('[data-theme="dark"]'));setDark(sections.some(el=>{const r=el.getBoundingClientRect();return r.top<65&&r.bottom>65}));};const scroll=()=>{if(!pending){pending=true;requestAnimationFrame(update)}};window.addEventListener('scroll',scroll,{passive:true});update();return()=>window.removeEventListener('scroll',scroll)},[pathname]);
 useEffect(()=>{
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const observed=new WeakSet<Element>();
  const animations:Animation[]=[];
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{
   if(!entry.isIntersecting)return;
   const el=entry.target as HTMLElement; observer.unobserve(el); el.classList.add('is-visible');
   if(reduced)return;
   const mode=el.dataset.reveal||((el.matches('.source-image,img')||el.classList.contains('featured'))?'mask':'rise');
   const delay=Number(el.dataset.delay||0);
   const frames=mode==='line'?[{clipPath:'inset(0 100% 0 0)',opacity:.2},{clipPath:'inset(0)',opacity:1}]:mode==='mask'?[{clipPath:'inset(100% 0 0 0)',transform:'translateY(24px)'},{clipPath:'inset(0)',transform:'translateY(0)'}]:mode==='tile'?[{opacity:0,transform:'translateY(-35px)',clipPath:'inset(0 0 100% 0)'},{opacity:1,transform:'translateY(0)',clipPath:'inset(0)'}]:[{opacity:0,transform:'translateY(28px)'},{opacity:1,transform:'translateY(0)'}];
   animations.push(el.animate(frames,{duration:mode==='mask'?900:mode==='line'?800:650,delay,easing:'cubic-bezier(.22,.7,.15,1)',fill:'backwards'}));
  }),{threshold:0,rootMargin:'0px 0px -24px 0px'});
  const attach=()=>document.querySelectorAll('.reveal:not(.is-visible)').forEach(el=>{if(!observed.has(el)){observed.add(el);observer.observe(el)}});
  attach();const mo=new MutationObserver(attach);mo.observe(document.body,{childList:true,subtree:true});
  return()=>{observer.disconnect();mo.disconnect();animations.forEach(a=>a.cancel())};
 },[pathname]);
 const mutate=async(action:string,line:Line)=>{if(lock.current||!ready)return false;lock.current=true;setBusy(true);try{const r=await fetch('/api/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,line})});const d=await r.json() as {error?:string;lines:Line[]};if(!r.ok)throw Error(d.error);setLines(d.lines);return true}catch(e){toast.error(e instanceof Error?e.message:'Your bag could not be saved. Please try again.');return false}finally{setBusy(false);lock.current=false}};
 const add=async(l:Line)=>{const ok=await mutate('add',l);if(ok){setQuickId(null);setCart(true);toast.success('Added to your bag')}return ok};
 const change=async(l:Line,q:number)=>{await mutate('set',{...l,quantity:q})};
 const go=(url:string)=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){router.push(url);return}if(tiles)return;const selected=new URL(url,window.location.origin).searchParams.get('category');setCategoryCover(selected?categories.indexOf(selected):null);setTiles(true);timers.current.push(setTimeout(()=>{router.push(url);window.scrollTo({top:0,behavior:'instant'});},370));timers.current.push(setTimeout(()=>{setTiles(false);setCategoryCover(null);document.querySelector<HTMLElement>('main h1')?.focus({preventScroll:true})},1050))};
 const quick=(id:string)=>{setSize('');setQuickId(id)};
 useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!mc)return;const ctrl=new AbortController();Promise.resolve(mc.registerTool({name:'search_vyrn_products',description:'Read matching products in the VYRN preview catalog.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},execute:({query}:{query:string})=>{if(typeof query!=='string'||query.length>100)throw Error('Query must be a string of up to 100 characters');return products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase())).map(({id,name,price,color})=>({id,name,price,currency:'EUR',color}))}},{signal:ctrl.signal})).catch(()=>{});return()=>ctrl.abort()},[]);
 const value={lines,busy,ready,paymentReady,add,change,openCart:()=>setCart(true),quick,go};
 return <Context.Provider value={value}>{pathname==='/'&&<OpeningSequence/>}<a className="skip" href="#main">Skip to content</a><header className={`header ${dark?'dark':''} ${compact?'compact':''}`}><nav className="nav-left" aria-label="Main navigation"><Go href="/collection">Shop</Go><Go href="/#collection">Collections</Go><Go href="/journal">Journal</Go></nav><Go href="/" className="wordmark" aria-label="VYRN home">VYRN<span>®</span></Go><div className="nav-right"><Go className="about-link" href="/info/about">About</Go><button aria-label="Search products" onClick={()=>setSearch(true)}><Search size={18}/></button><button className="account-link" aria-label="Your account" onClick={()=>router.push('/info/account')}><UserRound size={17}/></button><button aria-label={`Open shopping bag, ${lines.reduce((a,l)=>a+l.quantity,0)} items`} onClick={()=>setCart(true)}><ShoppingBag size={18}/><span className="bag-count">{lines.reduce((a,l)=>a+l.quantity,0)}</span></button><button aria-label="Open menu" onClick={()=>setMenu(true)}><Menu size={20}/></button></div></header>{children}<Footer/>
 <Sheet open={cart} onOpenChange={setCart}><SheetContent className="cart-sheet"><SheetHeader><SheetTitle>Your bag <span className="muted">({lines.reduce((a,l)=>a+l.quantity,0)})</span></SheetTitle><SheetDescription>Considered pieces. Collected by you.</SheetDescription></SheetHeader><div className="bag-lines">{!ready?<p>Loading your bag…</p>:!lines.length?<div className="empty-bag"><ShoppingBag size={42} strokeWidth={1}/><h3>A little room for something new.</h3><button className="button" onClick={()=>{setCart(false);router.push('/collection')}}>Explore the collection</button></div>:lines.map(l=>{const p=getProduct(l.id)!;return <article className="bag-line" key={lineKey(l)}><Go href={`/product/${p.id}`}><SourceImage crop={p.image} alt={p.name}/></Go><div><Go href={`/product/${p.id}`}>{p.name}</Go><p className="muted">{l.color} / {l.size}</p><b>{money(p.price)}</b><div className="quantity"><button aria-label={`Decrease ${p.name} quantity`} disabled={busy} onClick={()=>change(l,l.quantity-1)}><Minus size={14}/></button><span>{l.quantity}</span><button aria-label={`Increase ${p.name} quantity`} disabled={busy||l.quantity>=p.stock} onClick={()=>change(l,l.quantity+1)}><Plus size={14}/></button><button aria-label={`Remove ${p.name}`} disabled={busy} onClick={()=>change(l,0)}><Trash2 size={14}/></button></div></div></article>})}</div>{lines.length>0&&<div className="bag-total"><p><span>Subtotal</span><b>{money(subtotal(lines))}</b></p><p className="muted">Shipping calculated at checkout.</p><button className="button" disabled={busy} onClick={()=>{setCart(false);router.push('/checkout')}}>Continue to checkout</button><small>Private collection preview · illustrative prices</small></div>}</SheetContent></Sheet>
 <Sheet open={menu} onOpenChange={setMenu}><SheetContent className="menu-sheet"><SheetHeader><SheetTitle>VYRN</SheetTitle><SheetDescription>A wardrobe, on your terms.</SheetDescription></SheetHeader><nav><button onClick={()=>{setMenu(false);setSearch(true)}}>Search</button>{[['Shop all','/collection'],['Collections','/#collection'],['VYRN Studio','/#studio'],['Journal','/journal'],['About','/info/about'],['Contact','/info/contact'],['Your VYRN','/info/account']].map(([n,h])=><Go key={h} href={h} onClick={()=>setMenu(false)}>{n}</Go>)}</nav><p className="mono">INDEPENDENT EXPRESSION. EVERY DAY.</p></SheetContent></Sheet>
 <Dialog open={search} onOpenChange={setSearch}><DialogContent className="search-dialog"><DialogTitle>Find your next essential.</DialogTitle><DialogDescription>Search by product, style or category.</DialogDescription><label className="search-field"><Search size={20}/><input autoFocus aria-label="Search the collection" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Jackets, knitwear, hoodies…"/></label><div className="search-results">{products.filter(p=>`${p.name} ${p.category} ${p.type}`.toLowerCase().includes(query.toLowerCase())).map(p=><Go key={p.id} href={`/product/${p.id}`}><SourceImage crop={p.image} alt={p.name}/><span>{p.name}<small>{p.color}</small></span><b>{money(p.price)}</b></Go>)}{!products.some(p=>`${p.name} ${p.category} ${p.type}`.toLowerCase().includes(query.toLowerCase()))&&<p>No pieces match “{query}”. Try a different word.</p>}</div></DialogContent></Dialog>
 <Dialog open={!!quickProduct} onOpenChange={v=>!v&&setQuickId(null)}><DialogContent className="quick-dialog"><DialogTitle>{quickProduct?.name}</DialogTitle><DialogDescription>Select your size to add this piece to your bag.</DialogDescription>{quickProduct&&<><SourceImage crop={quickProduct.image} alt={quickProduct.name}/><div className="between"><span>{quickProduct.color}</span><b>{money(quickProduct.price)}</b></div><div className="sizes" aria-label="Size">{quickProduct.sizes.map(s=><button key={s} aria-pressed={size===s} onClick={()=>setSize(s)}>{s}</button>)}</div><button className="button" disabled={!size||busy||!ready} onClick={()=>add({id:quickProduct.id,size,color:quickProduct.color,quantity:1})}>{busy?'Adding…':size?'Add to bag':'Select a size'}</button><Go className="underlink" href={`/product/${quickProduct.id}`}>View full details</Go></>}</DialogContent></Dialog>
 <div className={`tile-transition ${tiles?'active':''}`} aria-hidden="true">{Array.from({length:60},(_,i)=><i key={i} style={{animationDelay:`${(i%10+Math.floor(i/10))*17}ms`}}/>)}</div>{categoryCover!==null&&categoryCover>=0&&<div className="look-navigation" aria-hidden="true"><Model index={categoryCover}/><span className="mono">{categories[categoryCover]}</span></div>}<Toaster position="bottom-center" theme="light"/></Context.Provider>
}
function Footer(){const [email,setEmail]=useState(''),[state,setState]=useState('idle');const submit=async(e:React.FormEvent)=>{e.preventDefault();setState('saving');try{const r=await fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});if(!r.ok)throw Error();setState('done')}catch{setState('error')}};return <footer data-theme="dark"><div className="footer-top"><div><p className="eyebrow">STAY IN THE LOOP</p><h2>First to know.<br/>Always yourself.</h2></div><form onSubmit={submit}>{state==='done'?<p role="status">You’re on the list. Thank you for being here.</p>:<><label htmlFor="newsletter">Collection notes, new drops and studio stories.</label><div className="newsletter"><input id="newsletter" type="email" value={email} required maxLength={254} onChange={e=>setEmail(e.target.value)} placeholder="Your email address"/><button disabled={state==='saving'}>{state==='saving'?'Joining…':'Join the list'}</button></div><small>By subscribing, you agree to our <Go href="/info/privacy">privacy notice</Go>. Unsubscribe via our contact form.</small>{state==='error'&&<p role="alert">We couldn’t save your email. Please try again.</p>}</>}</form></div><div className="footer-links"><span className="mono">INDEPENDENT EXPRESSION.<br/>NO UNIFORM REQUIRED.</span><div>{['Shop','Journal','About'].map((n,i)=><Go key={n} href={['/collection','/journal','/info/about'][i]}>{n}</Go>)}</div><div>{['Contact','FAQs','Shipping','Returns'].map(n=><Go key={n} href={`/info/${n.toLowerCase()}`}>{n}</Go>)}</div><div><Go href="/info/privacy">Privacy</Go><Go href="/info/terms">Terms</Go><span>EUR / EN</span></div></div><div className="footer-logo">VYRN<span>®</span></div><div className="footer-bottom"><span>© 2026 VYRN</span><span>Designed for who you are.</span><span className="footer-credit">Made by <a href="https://github.com/sakshamfit" target="_blank" rel="noopener noreferrer">sakshamfit</a></span><Go href="#top">Back to top</Go></div></footer>}
