import {notFound} from 'next/navigation';
import {Go} from '@/components/store/provider';
import {ContactForm} from '@/components/store/contact';
const copy:Record<string,{title:string;intro:string;sections:[string,string][]}>={
 about:{title:'Independent by design.',intro:'VYRN is a space for modern essentials and independent expression. Our collection explores the relationship between the everyday and the unexpected.',sections:[['The studio','We look at clothing through silhouette, material and cultural context. Generous proportions, considered layers and restrained color create room for individual interpretation.'],['Your point of view','What you wear should echo who you are. VYRN brings the pieces together. You decide how they belong.']]},
 shipping:{title:'Shipping.',intro:'VYRN is currently in private preview. We are not accepting paid orders yet.',sections:[['Planned delivery','The checkout currently shows illustrative delivery options for France: standard delivery at €8, or free from €250; express delivery at €15. These estimates are not an active shipping offer. Final destinations, prices and delivery windows will be confirmed before launch.'],['Before you pay','The final delivery amount and any applicable taxes will be displayed in secure checkout. No shipment is created by adding an item to your bag during the preview.']]},
 returns:{title:'Returns.',intro:'No purchases are being accepted during the private preview.',sections:[['Launch information','A complete returns policy, including eligibility, time limits, return address and refund process, will be published before the store accepts orders.'],['Questions','Please use the contact form if you have a question about a piece or the upcoming collection.']]},
 privacy:{title:'Privacy notice.',intro:'This private preview stores only the information needed for the features you choose to use.',sections:[['Your shopping bag','An essential browser cookie identifies your saved bag. The cookie is HttpOnly and lasts up to 30 days. Bag contents are stored on the server. No advertising trackers or marketing cookies are used.'],['Subscriptions and enquiries','When you join the list, your email address and signup time are saved. Contact enquiries save your name, email, message and submission time. These records are available to the site owner for handling your request. No marketing email is sent automatically from this preview.'],['Your choices','To request removal of a subscription, enquiry or other submitted information, use the contact form. You can remove items from your bag at any time.'],['Payments','This preview does not collect card information. If checkout is enabled after merchant review, payment details are entered directly with the payment provider. The merchant identity and complete privacy terms must be confirmed before public launch.']]},
 terms:{title:'Preview terms.',intro:'This website is a private preview of the VYRN storefront and creative direction.',sections:[['Collection information','Imagery, product descriptions, sizes, stock limits and prices are reference or illustrative content. They are not a confirmed offer for sale. Some imagery has been reconstructed from the supplied visual references.'],['Ordering','Adding items to a bag does not place an order. Payment is disabled in this preview. An order confirmation is only displayed after the payment provider verifies a completed payment.'],['Public launch','Verified merchant identity, product specifications, inventory, tax treatment, shipping and consumer terms must be completed before accepting live orders.']]},
 account:{title:'Your VYRN.',intro:'You can explore the collection and keep a saved bag without creating an account.',sections:[['Your saved selection','Your bag is linked to this browser using an essential cookie. Return on the same browser to continue your selection. Cross-device accounts are not available during the preview.'],['Order support','For questions about the collection, use the contact form. Paid orders are not open yet.']]},
 contact:{title:'Let’s talk.',intro:'Questions about the collection, collaborations or the studio? Leave an enquiry below.',sections:[]},
 faqs:{title:'A few answers.',intro:'The essentials about this VYRN preview.',sections:[['Can I place an order?','Not yet. You can discover products, select sizes and save a bag. Checkout remains closed until the store is ready for launch.'],['Will my bag be saved?','Yes. Your selection is stored securely and linked to this browser with an essential cookie. Keep using the same browser to return to it.'],['How do the pieces fit?','The direction is relaxed and oversized. Verified garment measurements will be published before sales open; the preview size labels are not a final fit guide.'],['Do you ship internationally?','The preview currently shows delivery estimates for France only. Final shipping destinations will be confirmed at launch.'],['Are the product images interactive 3D?','No. The current collection uses still photography and animated compositions. Product rotation will only be offered where a genuine 3D asset is available.']]}
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return {title:copy[slug]?.title||'Information'}}
export default async function Info({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=copy[slug];if(!page)notFound();return <main id="main" className="page-shell"><p className="eyebrow">VYRN / {slug.toUpperCase()}</p><h1 className="page-title">{page.title}</h1><div className="info-layout"><p>{page.intro}</p>{page.sections.map(([title,body])=>slug==='faqs'?<details key={title}><summary>{title}</summary><p>{body}</p></details>:<section key={title}><h2>{title}</h2><p>{body}</p></section>)}{slug==='contact'?<ContactForm/>:slug==='about'?<Go className="button" href="/collection">Explore the collection</Go>:<Go className="underlink" href="/info/contact">Contact the studio</Go>}</div></main>}
